# RESOURCE META SECTION
name: siva-model-lens # Lens Resource name (mandatory)
version: v1alpha # Lens manifest version (mandatory)
layer: user # DataOS Layer (optional)
type: lens # Type of Resource (mandatory)
tags: # Tags (optional)
  - lens
  - Data Hands On
description: This data model provides comprehensive insights for hotel booking analysis. # Lens Resource description (optional)

# LENS-SPECIFIC SECTION
lens:
  compute: runnable-default # Compute Resource that Lens should utilize (mandatory)
  secrets: 
    - name: sivagithub-r # Referred Instance Secret name (mandatory)
      allKeys: true # All keys within the secret are required or not (optional)

# Data Source configuration      
  source: 
    type: depot # Source type (could be themis, minerva flash as well)
    name: lakehouse # Source name (name of the depot)
    catalog: lakehouse # Catalog name for the depot
  repo: # Lens model code repository configuration (mandatory)
    url: https://github.com/Siva1316/Data_Os_deployment # URL of repository containing the Lens model (mandatory)
    lensBaseDir: Data_Os_deployment/Data_OS_Hands_On/Sematic_model/Model # Relative path of the Lens 'model' directory in repository (mandatory)
    syncFlags: # Additional flags used during synchronization (optional)
      - --ref=main # Repository Branch (optional)

# API Instances configuration
  api:  #(optional)
    replicas: 1 # Number of API instance replicas (optional)
    logLevel: info # Logging granularity (optional)
    resources: # CPU and memory configurations for API Instances (optional)
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1048Mi

# Worker configuration
  worker:  #(optional)
    replicas: 1 # Number of Worker replicas (optional)
    logLevel: debug # Logging level for Worker (optional)
    resources: # CPU and memory configurations for Worker (optional)
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1248Mi

# Router configuration

  router:  #(optional)
    logLevel: info # Level of log detail for Router (optional)
    resources: # CPU and memory resource specifications for the router (optional)
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 2548Mi

# Iris configuration 
  iris: #(optional)
    logLevel: info # Log level for Iris (optional)
    resources: # CPU and memory resource specifications for the iris board (optional)
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1600m
        memory: 2240Mi
# Metric configuration 
  metric:                         #(optional)
    logLevel: info # Log level for metrics (optional)