name: product-siva-datahandson-api
version: v1
type: service
tags:
  - service
  - dataos:type:resource
  - dataos:resource:service
  - dataos:layer:user
description: Talos Service
workspace: public
service:
  servicePort: 3000
  ingress:
    enabled: true
    stripPath: true
    path: /talos/public:product-siva-datahandson-api
    noAuthentication: true
  replicas: 1
  logLevel: DEBUG
  compute: runnable-default
  envs:
    TALOS_SCHEMA_PATH: Data_Os_Handson/Activation_Folder/Data_API
    TALOS_BASE_PATH: /talos/public:product-siva-datahandson-api
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  stack: talos:2.0
  dataosSecrets:
    - name: bitbucket-cred
      allKeys: true
  stackSpec:
    repo:
      url: https://github.com/Siva1316/Data_Os_Handson
      projectDirectory: Data_Os_Handson/Activation_Folder/Data_API
      syncFlags:
        - --ref=main